apiVersion: v1
kind: Service
metadata:
  name: todo-web
  labels:
    kiamol: ch10-lab
spec:
  ports:
    - port: 8081
      targetPort: 80
  selector:
    app: todo-web
    environment: test
  type: LoadBalancer